language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'
install:
  - pip install coveralls
script: nosetests --with-coverage --cover-branch --cover-package=simpletex
after_success:
  - coveralls
